<a href="https://colab.research.google.com/github/Ashmie11/MLTSA25_AshmieThapa/blob/main/Inclass/MLTSA25_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_str = "hello"


In [34]:

print(my_str)

hello


In [ ]:
my_int=36

In [ ]:
my_float=36,

In [8]:

print(my_float)

36.0


In [ ]:
my_int+ my_float

In [ ]:
my_int* my_str

In [ ]:
helloworld= "Hello" + "World!"

In [ ]:
import numpy as np

In [33]:
my_nparr = np.array([1, 2, 3, 4, 5])


In [ ]:
my_bool=True

In [9]:
my_int=1

In [10]:
my_int!=6

True

In [11]:
my_int = 10

if my_int != 6:
    print("my_int is not 6")
else:
    print("It was 6!!")



my_int is not 6


In [12]:
type(my_int)

int

In [22]:


my_nparr = np.array([1, 2, 3, 4, 5])


int64


In [31]:
print(my_nparr.dtype)

int64


In [ ]:
my_nparr.max()

In [ ]:
my_nparr.argmax()

In [23]:
my_nparr[0]

1

In [24]:
my_nparr[2]

3

In [25]:
my_nparr[-1]

5

In [26]:
my_nparr[1:]

array([2, 3, 4, 5])

In [27]:
my_nparr[1:2]

array([2])

In [ ]:
my_nparr[1:3]

In [28]:
list(range(1,4))

[1, 2, 3]

In [40]:

for a in range(1, 4):
  print(sum(np.arange(0, a)))

0
1
3


In [43]:
for a in range(1, 4):
  print(a,np.arange(0,a).sum())

1 0
2 1
3 3


In [38]:
np.arange(0, a)

array([0, 1, 2])

In [53]:
def all_odds(lastn):
    """
    Returns a list of odd numbers up to lastn (inclusive).

    Parameters:
        lastn (int): The last number in the range.

    Returns:
        list: A list of odd numbers.
    """
    if not isinstance(lastn, int) or lastn < 1:
        raise ValueError("Input must be a positive integer.")

    odds = list(range(1, lastn + 1, 2))
    print(f"Odd numbers up to {lastn}: {odds}")
    return odds


In [55]:
result = all_odds(10)


Odd numbers up to 10: [1, 3, 5, 7, 9]


In [64]:
def is_palindrome(word):
    """
    Checks if the input word is a palindrome.

    Parameters:
        word (str): The word to check.

    Returns:
        bool: True if the word is a palindrome, False otherwise.
    """
    if not isinstance(word, str):  # Check if the input is a string
        print("Error: The input is not a string.")
        return False

    word = word.lower()  # Convert to lowercase for case-insensitivity
    return word == word[::-1]  # Compare the word with its reverse

In [65]:
print(is_palindrome("madam"))
print(is_palindrome("hello"))
print(is_palindrome("Racecar"))
print(is_palindrome(12345))

True
False
True
Error: The input is not a string.
False


In [68]:
def ispalindrome(s):
 "checks if a string is a palindrome"
  #if type(s)!= str:
   #print("is not a string")
 assert type(s) == str, "is not a string"
 if s.lower() == s[::-1].lower():
   return True
 return False

ispalindrome("tacocat")




True

In [67]:
s= "palindrome"
s[::-1]


'emordnilap'